# Generated by Django 5.2.7 on 2025-10-22 16:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('spot_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Spot ID')),
                ('spot_sector_id', models.IntegerField(blank=True, null=True, verbose_name='Spot Sector ID')),
                ('spot_type_id', models.IntegerField(blank=True, null=True, verbose_name='Spot Type ID')),
                ('spot_settlement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Settlement (Colonia)')),
                ('spot_municipality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Municipality')),
                ('spot_state', models.CharField(blank=True, max_length=255, null=True, verbose_name='State')),
                ('spot_region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Region')),
                ('spot_corridor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Corridor')),
                ('spot_address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Geographic Location')),
                ('spot_latitude', models.FloatField(blank=True, null=True)),
                ('spot_longitude', models.FloatField(blank=True, null=True)),
                ('spot_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('spot_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('spot_area_in_sqm', models.FloatField(blank=True, null=True, verbose_name='Area (sqm)')),
                ('spot_price_sqm_mxn_rent', models.FloatField(blank=True, null=True, verbose_name='Price per sqm Rent (MXN)')),
                ('spot_price_total_mxn_rent', models.FloatField(blank=True, null=True, verbose_name='Total Price Rent (MXN)')),
                ('spot_price_sqm_mxn_sale', models.FloatField(blank=True, null=True, verbose_name='Price per sqm Sale (MXN)')),
                ('spot_price_total_mxn_sale', models.FloatField(blank=True, null=True, verbose_name='Total Price Sale (MXN)')),
                ('spot_maintenance_cost', models.FloatField(blank=True, null=True, verbose_name='Maintenance Cost (MXN)')),
                ('spot_modality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modality (Rent/Sale/Both)')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='User ID')),
                ('spot_created_date', models.DateField(blank=True, null=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Spot',
                'verbose_name_plural': 'Spots',
                'ordering': ['spot_id'],
            },
        ),
    ]
