# Generated by Django 5.2.7 on 2025-10-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='data_source',
            field=models.CharField(default='csv', help_text="Source of the data (e.g., 'csv', 'json')", max_length=10),
        ),
        migrations.AddField(
            model_name='spot',
            name='public_id',
            field=models.CharField(blank=True, help_text='Public ID from external source (e.g., EB-PV4135)', max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='spot',
            index=models.Index(fields=['location'], name='spots_spot_locatio_c31c71_idx'),
        ),
    ]
